spring.application.name=trip-service

spring.datasource.url=jdbc:mysql://localhost:3306/travel_trip
spring.datasource.username=root
spring.datasource.password=cdac

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8083