spring.application.name=WEATHER-SERVICE

server.port=8084

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Open Meteo API
openmeteo.base.url=https://api.open-meteo.com/v1

# Maps Service (through API Gateway)
maps.service.url=http://MAPS-SERVICE
spring.cloud.compatibility-verifier.enabled=false