spring.application.name=preference-service

server.port=8086

spring.datasource.url=${PREFERENCE_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=${EUREKA_URL}
spring.cloud.compatibility-verifier.enabled=false