CREATE DATABASE IF NOT EXISTS travel_auth;
CREATE DATABASE IF NOT EXISTS travel_user;
CREATE DATABASE IF NOT EXISTS travel_trip;
CREATE DATABASE IF NOT EXISTS travel_destination;
CREATE DATABASE IF NOT EXISTS travel_preference;