server.port=8088

spring.application.name=AI-SERVICE

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

openrouter.api.key=${OPENROUTER_API_KEY}
openrouter.api.model=deepseek/deepseek-chat
