server.port=8088

spring.application.name=AI-SERVICE

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# OpenRouter API
openrouter.api.key=xxxxxxxxxxxxx
openrouter.api.model=deepseek/deepseek-chat
